version: "3.8"

services:
  my-sba:
    image: openjdk:17-jdk-alpine
    container_name: mysbaimage
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - my-db
    networks:
      - my-net
    volumes:
      - ./build/libs/SmartCityWasteManagement-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  my-db:
    image: mongo:5.0
    container_name: mongodbimage
    command: --replSet rs0
    ports:
      - 27017:27017
    networks:
      - my-net
    volumes:
      - mongodata:/data/db

  mongodb-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - my-net
    environment:
      ME_CONFIG_MONGODB_SERVER: my-db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

networks:
  my-net:
    driver: "bridge"

volumes:
  mongodata:
